version: '3'
services:
  job:
    build:
      context: python_job/
    volumes:
      - ./python_job/scripts/:/app/scripts/
    restart: always
    container_name: python-cronjob
    command: /app/entrypoint.sh
